apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    #- port: 80
    - name: http
      port: 5000
      #nodePort: 32256
  selector:
    app: app
    tier: app
  #type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "127.0.0.1:30400/app:latest"
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 5000


---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: app-gateway

  spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 80
        name: http-app
        protocol: HTTP
      hosts:
      - "*"
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: app-vs

  spec:
    hosts:
    - "*"
    gateways:
    - app-gateway
    http:
    - match:
      - port: 80
      route:
      - destination:
          host: app
          port:
            number: 5000
